import { TodoList } from '@models/index';

export const todos: TodoList[] = [
  {
    icon: 'list-icon-1',
    id: 'home',
    name: 'Home',
    todos: [
      {
        id: '1',
        todoListId: 'list-1',
        isComplete: true,
        description: 'Buy groceries',
        createdAt: '2023-10-12T08:00:00Z',
        completedAt: undefined,
      },
      {
        id: '2',
        todoListId: 'list-1',
        isComplete: false,
        description: 'Pay bills',
        createdAt: '2023-10-12T10:00:00Z',
        completedAt: undefined,
      },
      {
        id: '3',
        todoListId: 'list-1',
        isComplete: false,
        description: 'Schedule dentist appointment',
        createdAt: '2023-10-13T09:00:00Z',
        completedAt: undefined,
      },
      {
        id: '4',
        todoListId: 'list-1',
        isComplete: false,
        description: 'Finish report',
        createdAt: '2023-10-14T13:00:00Z',
        completedAt: undefined,
      },
      {
        id: '5',
        todoListId: 'list-1',
        isComplete: false,
        description: 'Call mom',
        createdAt: '2023-10-15T15:00:00Z',
        completedAt: undefined,
      },
      {
        id: '6',
        todoListId: 'list-1',
        isComplete: false,
        description: 'Plan weekend activities',
        createdAt: '2023-10-15T12:00:00Z',
        completedAt: undefined,
      },
      {
        id: '7',
        todoListId: 'list-1',
        isComplete: false,
        description: 'Read a chapter of a book',
        createdAt: '2023-10-16T09:00:00Z',
        completedAt: undefined,
      },
      {
        id: '8',
        todoListId: 'list-1',
        isComplete: false,
        description: 'Go for a walk',
        createdAt: '2023-10-17T08:00:00Z',
        completedAt: undefined,
      },
    ],
  },
  {
    icon: 'list-icon-1',
    id: 'list-1',
    name: 'List 1',
    todos: [
      {
        id: '1',
        todoListId: 'list-1',
        isComplete: true,
        description: 'Buy groceries',
        createdAt: '2023-10-12T08:00:00Z',
        completedAt: undefined,
      },
      {
        id: '2',
        todoListId: 'list-1',
        isComplete: false,
        description: 'Pay bills',
        createdAt: '2023-10-12T10:00:00Z',
        completedAt: undefined,
      },
      {
        id: '3',
        todoListId: 'list-1',
        isComplete: false,
        description: 'Schedule dentist appointment',
        createdAt: '2023-10-13T09:00:00Z',
        completedAt: undefined,
      },
      {
        id: '4',
        todoListId: 'list-1',
        isComplete: false,
        description: 'Finish report',
        createdAt: '2023-10-14T13:00:00Z',
        completedAt: undefined,
      },
      {
        id: '5',
        todoListId: 'list-1',
        isComplete: false,
        description: 'Call mom',
        createdAt: '2023-10-15T15:00:00Z',
        completedAt: undefined,
      },
      {
        id: '6',
        todoListId: 'list-1',
        isComplete: false,
        description: 'Plan weekend activities',
        createdAt: '2023-10-15T12:00:00Z',
        completedAt: undefined,
      },
      {
        id: '7',
        todoListId: 'list-1',
        isComplete: false,
        description: 'Read a chapter of a book',
        createdAt: '2023-10-16T09:00:00Z',
        completedAt: undefined,
      },
      {
        id: '8',
        todoListId: 'list-1',
        isComplete: false,
        description: 'Go for a walk',
        createdAt: '2023-10-17T08:00:00Z',
        completedAt: undefined,
      },
    ],
  },
  {
    icon: 'list-icon-2',
    id: 'list-2',
    name: 'List 2',
    todos: [
      {
        id: '13',
        todoListId: 'list-2',
        isComplete: false,
        description: 'Todo 1 for List 2',
        createdAt: '2023-10-12T11:00:00Z',
        completedAt: undefined,
      },
    ],
  },
];
